require:
  - rubocop-minitest
  - rubocop-performance

AllCops:
  TargetRubyVersion: 2.5

Layout/SpaceBeforeBlockBraces:
  Enabled: false

Layout/LineLength:
  Max: 120
  Exclude:
    - 'api/v01/entities/vrp_result.rb'

Metrics/MethodLength:
  Max: 30

Metrics/AbcSize:
  Enabled: false

Naming/MethodParameterName:
  MinNameLength: 1

Style/AsciiComments:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/MultilineTernaryOperator:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Layout/FirstHashElementIndentation:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Layout/CommentIndentation:
  Enabled: false

Layout/FirstArrayElementIndentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Layout/EndAlignment:
  EnforcedStyleAlignWith: keyword

Style/BlockDelimiters:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/RaiseArgs:
  EnforcedStyle: compact

Style/ParallelAssignment:
  Enabled: false

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true
