inherit_gem:
  mapotempo_rubocop:
    - rubocop-default.yml

AllCops:
  TargetRubyVersion: 2.5
  CacheRootDirectory: rubocop_cache
  Exclude:
    - 'tmp/**/*'
    - 'vendor/bundle/**/*'
    - 'config/initializers/local.rb'

Style/FrozenStringLiteralComment:
  Exclude:
    - 'config.ru'
    - 'Gemfile'
    - 'Rakefile'

# Layout/LineLength:
#   Enabled: false

Style/NumericPredicate:
  Enabled: false

Layout/EmptyLines:
  Severity: warning

Layout/ExtraSpacing:
  Severity: warning

Layout/IndentationWidth:
  Severity: warning

Layout/IndentationConsistency:
  Severity: warning
