require: rubocop-performance

AllCops:
  TargetRubyVersion: 2.3

Layout/LineLength:
  Enabled: false

Layout/SpaceBeforeBlockBraces:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Layout/ParameterAlignment:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  Enabled: true
  EnforcedStyle: compact

Style/NegatedIf:
  Enabled: false

Layout/FirstHashElementIndentation:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Layout/LeadingCommentSpace:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Layout/CommentIndentation:
  Enabled: false

Layout/FirstArrayElementIndentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Layout/IndentationWidth:
  Enabled: false

Layout/EndAlignment:
  Enabled: false

Layout/ElseAlignment:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Style/PreferredHashMethods:
  EnforcedStyle: verbose

Style/RedundantException:
  Enabled: false
